const phrases = [
  "It is all Donny's fault",
  "Justin has it handled",
  "Just check the google sheet",
  "Sell, Sell, Sell",
  "Donny’s fault, as always.",
  "Ask Donny, he’s probably messing it up.",
  "Justin’s got it...",
  "Google Sheet is the new Bible.",
  "Sell, Sell, Sell... Like Donny’s selling his dignity.",
  "Sell, Sell, Sell",
  "Lets handle it on our morning meetings",
  "Check the gear matrix",
  "I need you to invoice this",
  "Are you going to invoice this before we close the month?",
  "I’m out of office",
  "Check with Justin",
  "Check with Kim",
  "Check with Preston",
  "Kasey has it covered",
  "Hang on. Literally anyone else is calling me...",
  "Just blame New York, it's easier.",
  "Copy Donny? Why, do you hate yourself?",
  "Did you check the Google Sheet?",
  "Google Sheet says it’s Donny’s turn to screw up.",
  "Donny’s a pro at one thing: passing the blame.",
  "Tom Stinson says: Good luck with that.",
  "Have Kim bury that...",
  "Lets just hide that in NY expenses",
  "We can't send that, Donny might actually get credit.",
  "Justin’s got a plan... and it’s terrible.",
  "Well, you can do that because Justin is our Executive Packaging Strategist.",
  "Yeah, that’s Justin’s thing—he’s our Director of Spreadsheets",
  "Oh, don’t worry, Justin’s the Senior Manager of Making It Up As We Go.",
  "Didn’t you know? Justin’s the Vice President of Excuse Generation.",
  "Justin handles that—he’s our Lead Facilitator of Overcomplicated Solutions.",
  "You should ask Justin, he’s the Head of Delegated Disasters.",
  "Justin’s been around forever—he’s the Supreme Ruler of Last-Minute Fixes.",
  "Oh, Justin? He’s been promoted to Grandmaster of Unnecessary Meetings.",
  "Lets just send a dumb switch",
  "I dont have time for this R2 shit",
  "WE FUCKING CRUSHED INVETORY THIS YEAR",
  "40% loss, not bad.. not great",
  "I'm busy, check with Justin",
  "I'm busy, check with Preston",
  "Let's check with Justin first",
  "Thats not how we do it on Univision",
];

module.exports = phrases;
