const phrases = [
  "It is all Donny's fault",
  "Justin has it handled",
  "Just check the google sheet",
  "Sell, Sell, Sell",
  "Donny’s fault, as always.",
  "Ask Donny, he's probably messing it up.",
  "Justin’s got it...",
  "Google Sheet is the new Bible.",
  "Sell, Sell, Sell... Like Donny’s selling his dignity.",
  "Sell, Sell, Sell",
  "Lets handle it on our morning meetings",
  "Check the gear matrix",
  "I need you to invoice this",
  "Are you going to invoice this before we close the month?",
  "I’m out of office",
  "Check with Justin",
  "Check with Kim",
  "Check with Preston",
  "Kasey has it covered",
  "Hang on. Literally anyone else is calling me...",
  "Just blame New York, it's easier.",
  "Copy Donny? Why, do you hate yourself?",
  "Did you check the Google Sheet?",
  "Google Sheet says it’s Donny’s turn to screw up.",
  "Donny’s a pro at one thing: passing the blame.",
  "Tom Stinson says: Good luck with that.",
  "Lets just hide that in NY expenses",
  "We can't send that, Donny might actually get credit.",
  "Justin’s got a plan... and it’s terrible.",
  "Well, you can't do that because Justin is our Executive Packaging Strategist.",
  "Yeah, that’s Justin’s thing—he’s our Director of Spreadsheets",
  "Oh, don’t worry, Justin’s the Senior Manager of Making It Up As We Go.",
  "Didn’t you know? Justin’s the Vice President of Excuse Generation.",
  "Justin handles that—he’s our Lead Facilitator of Overcomplicated Solutions.",
  "You should ask Justin, he’s the Head of Delegated Disasters.",
  "Justin’s been around forever—he’s the Supreme Ruler of Last-Minute Fixes.",
  "Oh, Justin? He’s been promoted to Grandmaster of Unnecessary Meetings.",
  "Lets just send a dumb switch",
  "I dont have time for this R2 shit",
  "WE FUCKING CRUSHED INVETORY THIS YEAR",
  "40% loss, not bad.. not great",
  "I'm busy, check with Justin",
  "I'm busy, check with Preston",
  "Let's check with Justin first",
  "Thats not how we do it on Univision",
  "I'm currently out of office. Please contact Sales",
  "I'm out of office, so is the rest of the shop",
  "We closed early",
  "You want how many soldering irons?",
  "Justin, Kim, and I just lost power and society is falling apart due to the tropical storm, but Cody and Preston are at the shop if you need anything. ",
  "I gave my leg a test run on my 1 day Masque trip, and it didn’t go well so I’m no longer going to InfoComm.",
  "Donny has been spending too much.  Oh btw, I’m flying up tomorrow",
  "Can you make the transfer order for me?",
  "What is a transfer order?",
  "Lets see what Casandra has to say about this",
  "Are you going to add me to the crew list?",
  "What hotel are you putting me at?",
  "I don’t have time for this",
  "I'm out of office",
  "I'm out of office",
  "Add me to the list",
  "It's too late to add you to the list",
  "I can't change crew names anymore",
  "It's too late to change crew names",
  "Names are already submitted... We can't swap techs",
  "Do you think we can bill for this?",
  "We will never financially recover from this",
  "Just copy Donny",
  "It is all Donny’s fault",
  "I need you to invoice this",
  "Are you going to invoice this before we close the month?",
  "I’m out of office",
  "Add me to the list",
  "It's too late to add you to the list",
  "Add me to the list",
  "It's too late to add you to the list",
  "Boyle's on Vaction",
  "Boyle has a wedding",
  "What? Another wedding Boyle?",
  "Matt's on vacation",
  "Matt's on vacation",
  "Matt Boyle is in Japan again",
  "It's fashion week... Boyle has to take vacation. It's mandatory.",
  "Boyle will be in on Wednesday and Friday and then will be on vacation.",
  "Is it a full moon?, Boyle is probably on vacation",
  "Boyle has to take vacation",
  "Mercury is in retrograde... and Boyle has to take vacation",
];

module.exports = phrases;
